export const topics = [
  'Indian History',
  'Geography',
  'Indian Polity',
  'Economics',
  'General Science',
  'Environment & Ecology',
  'Art & Culture',
  'Current Affairs',
  'Quantitative Aptitude',
  'Reasoning Ability',
  'English Language',
  'Ancient History',
  'Medieval History',
  'Modern History',
  'World History',
  'Physical Geography',
  'Indian Geography',
  'World Geography',
  'Constitution of India',
  'Governance',
  'Social Justice',
  'International Relations',
  'Indian Economy',
  'Economic Development',
  'Physics',
  'Chemistry',
  'Biology',
  'Science & Technology',
  'Biodiversity',
  'Climate Change',
  'General Knowledge',
  'Verbal Reasoning',
  'Non-Verbal Reasoning',
  'Data Interpretation',
  'Reading Comprehension',
  'Grammar',
  'Vocabulary',
  'Indian Society',
  'Ethics, Integrity & Aptitude',
  'Disaster Management',
  'Internal Security',
  'Agriculture',
  'Government Schemes',
  'Sports',
  'Awards & Honors',
  'Summits & Conferences',
  'Important Days',
  'Books & Authors',
  'National & International Affairs',
  'Static GK',
  'Financial Awareness'
];
