CREATE TABLE revise (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    content jsonb not null,
    type text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table revise enable row level security;

create policy "Enable read access for own users"
on revise for select
using (auth.uid() = user_id);

create policy "Enable insert for own users"
on revise for insert
with check (auth.uid() = user_id);

create policy "Enable delete for own users"
on revise for delete
using (auth.uid() = user_id);
